import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        <nav>
          <a href="#" className="aitemmenu">Inicio</a>
          <a href="#" className="aitemmenu">Acerca de</a>
          <a href="/about" className="aitemmenu">Contacto</a>
          <a href="/clients" className="aitemmenu">Clientes</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
